<body style="background-color: #aaa;">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="#!"><b>Blog</b></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
             data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
              aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <li class="nav-item"><a class="nav-link" href="/admin">Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="/admin/blog">Blogs</a></li>
                </ul>
                <form class="d-flex">
                </form>
            </div>
        </div>
    </nav>
    <!-- Header-->
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">Blog Panel</h1>
                <p class="lead fw-normal text-white-50 mb-0">Blog Manage Here</p>
            </div>
        </div>
    </header>
    <!-- Section-->
    <main class="my-5">
        <div class="container">
            <!--Section: Content-->
            <section class="text-center">
                <h4 class="mb-5 p-4"><strong>Your's Blogs</strong></h4>
                <form action='/admin/update?id=<?php echo $data['_id'] ?>' method="POST">
                    <div class="row my-4">
                        <div class="col-md-3 col-sm-12">
                            <label for="title">Title:
                                <input type="text" name="title" id="title"
                                value="<?php echo $data["title"] ?>">
                            </label>
                        </div>
                        <div class="col-md-5 col-sm-12">
                            <textarea name="data" id="data" cols="30" rows="3" placeholder="Enter Your Data">
                            <?php  echo $data["data"] ?>
                            </textarea>
                        </div>
                        <div class="col-md-3 col-sm-8">
                            <select name="image" id="image">
                                <option value="<?php echo "$data[image]" ?>">
                                -Select-</option>
                                <option value="https://mdbootstrap.com/img/new/standard/nature/184.jpg">
                                    Nature Image</option>
                                <option value="https://mdbootstrap.com/img/new/standard/nature/023.jpg">
                                    Sea Image</option>
                                <option value="https://mdbootstrap.com/img/new/standard/nature/111.jpg">
                                    Mountain Image</option>
                                <option value="https://mdbootstrap.com/img/new/standard/nature/002.jpg">
                                    Landscape Image</option>
                                <option value="https://mdbootstrap.com/img/new/standard/nature/022.jpg">
                                    Sunrise Image</option>
                                <option value="https://mdbootstrap.com/img/new/standard/nature/035.jpg">
                                    Environment Image</option>
                            </select>
                        </div>
                        <div class="col-md-1 col-sm-4">
                            <input type="submit" class="btn btn-success" value="Update">
                        </div>
                    </div>
                </form>
                <?php
                    if ($_GET['msg'] == "fill_all") {
                        echo "<p class='text-center' style='color: red;' id='error'><b>Fill All Input</b></p>";
                    }
                ?>

            </section>
            <!--Section: Content-->

        </div>
    </main>
    <!-- Footer-->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p>
        </div>
    </footer>
</body>