<body>
    <?php
    require_once APP_PATH.'/views/header.phtml'
    ?>

    <!--Main Navigation-->

    <!--Main layout-->
    <main class="my-5">
        <div class="container">
            <!--Section: Content-->
            <section class="text-center">
                <h4 class="mb-5 p-4"><strong>Your's Blogs</strong></h4>
                <form action='/blog/update?id=<?php echo $data['_id'] ?>' method="POST">
                    <div class="row my-4">
                        <div class="col-md-3 col-sm-12">
                            <label for="title">Title:
                                <input type="text" name="title" id="title"
                                value="<?php echo $data["title"] ?>">
                            </label>
                        </div>
                        <div class="col-md-5 col-sm-12">
                            <textarea name="data" id="data" cols="30" rows="3" placeholder="Enter Your Data">
                            <?php  echo $data["data"] ?>
                            </textarea>
                        </div>
                        <div class="col-md-3 col-sm-8">
                            <select name="image" id="image">
                                <option value="<?php echo "$data[image]" ?>">
                                -Select-</option>
                                <option value="https://mdbootstrap.com/img/new/standard/nature/184.jpg">
                                    Nature Image</option>
                                <option value="https://mdbootstrap.com/img/new/standard/nature/023.jpg">
                                    Sea Image</option>
                                <option value="https://mdbootstrap.com/img/new/standard/nature/111.jpg">
                                    Mountain Image</option>
                                <option value="https://mdbootstrap.com/img/new/standard/nature/002.jpg">
                                    Landscape Image</option>
                                <option value="https://mdbootstrap.com/img/new/standard/nature/022.jpg">
                                    Sunrise Image</option>
                                <option value="https://mdbootstrap.com/img/new/standard/nature/035.jpg">
                                    Environment Image</option>
                            </select>
                        </div>
                        <div class="col-md-1 col-sm-4">
                            <input type="submit" class="btn btn-success" value="Update">
                        </div>
                    </div>
                </form>
                <?php
                    if ($_GET['msg'] == "fill_all") {
                        echo "<p class='text-center' style='color: red;' id='error'><b>Fill All Input</b></p>";
                    }
                ?>

            </section>
            <!--Section: Content-->

        </div>
    </main>
    <!--Main layout-->

    <!--Footer-->
    <footer class="bg-light text-lg-start">
        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
            © 2020 Copyright:
            <a class="text-dark" href="">CEDCOSS.com</a>
        </div>
        <!-- Copyright -->
    </footer>
    <!--Footer-->
</body>