<body>
    <header>
        <!-- Intro settings -->
        <style>
            #intro {
                /* Margin to fix overlapping fixed navbar */
                margin-top: 58px;
            }

            @media (max-width: 991px) {
                #intro {
                    /* Margin to fix overlapping fixed navbar */
                    margin-top: 45px;
                }
            }
        </style>

        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
            <div class="container-fluid">
                <!-- Navbar brand -->
                <span class="navbar-brand" href="">
                    <b>Blog</b>
                </span>
                    <ul class="navbar-nav d-flex flex-row me-auto mb-2 mb-lg-0">
                        <li class="nav-item active me-1">
                            <a class="nav-link" aria-current="page" href="/">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/login" rel="nofollow">My Blog</a>
                        </li>
                    </ul>

                    <ul class="navbar-nav d-flex flex-row">
                        <!-- Button -->
                        <li class="nav-item me-3 me-lg-0">
                            <a class="nav-link" href="./login">
                                <button class="bg-primary p-1">login</button>
                            </a>
                        </li>
                    </ul>
            </div>
        </nav>
        <!-- Navbar -->

    </header>
    <!--Main Navigation-->

    <!--Main layout-->
    <main class="my-5">
        <div class="container">
            <!--Section: Content-->
            <section class="text-center ">
                <h4 class="mb-5 p-4"><strong>Latest posts</strong></h4>

                <div class="row">
                    <?php
                    echo $blog;
                    ?>
                </div>
            </section>
            <!--Section: Content-->

        </div>
    </main>
    <!--Main layout-->

    <!--Footer-->
    <footer class="bg-light text-lg-start">
        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
            © 2020 Copyright:
            <a class="text-dark" href="">CEDCOSS.com</a>
        </div>
        <!-- Copyright -->
    </footer>
    <!--Footer-->
</body>