<header>
        <!-- Intro settings -->
        <style>
            #intro {
                /* Margin to fix overlapping fixed navbar */
                margin-top: 58px;
            }

            @media (max-width: 991px) {
                #intro {
                    /* Margin to fix overlapping fixed navbar */
                    margin-top: 45px;
                }
            }
        </style>

        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
            <div class="container-fluid">
                <!-- Navbar brand -->
                <span class="navbar-brand">
                    <b>Blog</b>
                </span>
                <div class="collapse navbar-collapse" id="navbarExample01">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item active">
                            <a class="nav-link" aria-current="page" href="/index/login">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/blog" rel="nofollow">My Blog</a>
                        </li>
                    </ul>
                    
                    <ul class="navbar-nav d-flex flex-row">
                        <!-- Button -->
                        <li class="nav-item me-3 me-lg-0">
                            <a class="nav-link" href="/">
                                <button class="bg-primary p-1">sign out</button>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Navbar -->

    </header>